apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-test
  labels:
    app: git-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-test
  template:
    metadata:
      labels:
        app: microsvc
    spec:
      containers:
      - name: git-test
        image: kkimmin/git-test:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8110
        env:
        - name: PORT
          value: "8000"
