apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: git-test
  template:
    metadata:
      labels:
        run: git-test
    spec:
      containers:
      - image: kkimmin/git-test:37
        name: git-test
        ports:
        - containerPort: 80
